name: Close Issues
on:
  issues:
    types: [opened]

jobs:
  close_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Encode issue body to base64
      id: encode_body
      run: |
        echo "::set-output name=body_base64::$(echo -n '${{ github.event.issue.body }}' | base64)"

    - name: Check issue body for regex
      id: check_regex
      run: |
        ISSUE_BODY=$(echo "${{ steps.encode_body.outputs.body_base64 }}" | base64 --decode)
        if [[ ! $ISSUE_BODY =~ 345567 ]]; then
          echo "::set-output name=should_close::true"
        else
          echo "::set-output name=should_close::false"
        fi

    - name: Close issue
      if: steps.check_regex.outputs.should_close == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            state: 'closed'
          })
